### ISSUE TITLE
Exclude folder names, for example `node_modules`

### ISSUE THREAD

**Issue by Akryum** [teejee2008/timeshift#499] opened 2019-10-18 12:53 UTC
**Is your feature request related to a problem? Please describe.**
Being a JS developer, I can't really make backup with all the `node_modules` folders scattered throughout the dozens of JS projects in my home directory.

**Describe the solution you'd like**
A way to add folder name patterns in the filters.

**Describe alternatives you've considered**
#290 

**Additional context**
Currently, we can't add simple rsync filter like `'node_modules'` to the filter list (they get deleted when saving).

**Comment by Akryum** [comment] 2019-10-18 12:54
Workaround for now: ignore the folder containing JS projects.

**Comment by karvex** [comment] 2019-11-17 23:56
It's possible to ignore node_modules either by adding exclude pattern as "node_modules" or "node_modules/** and drag it on top.

![image](https://user-images.githubusercontent.com/1015258/69016378-2a74c580-099e-11ea-88f1-0b1de4c9a5fd.png)

**Comment by adelin-b** [comment] 2020-06-20 20:30
> @Akryum It's possible to ignore node_modules either by adding exclude pattern as "node_modules" or "node_modules/** and drag it on top.
> 
> ![image](https://user-images.githubusercontent.com/1015258/69016378-2a74c580-099e-11ea-88f1-0b1de4c9a5fd.png)

It does not work, it disappears on save.

**Comment by ThanosDi** [comment] 2020-07-28 13:11
> > @Akryum It's possible to ignore node_modules either by adding exclude pattern as "node_modules" or "node_modules/** and drag it on top.
> > ![image](https://user-images.githubusercontent.com/1015258/69016378-2a74c580-099e-11ea-88f1-0b1de4c9a5fd.png)
> 
> It does not work, it disappears on save.

Same here, any alternative ways?

**Comment by Xaz16** [comment] 2020-07-30 09:06
Suffering from this one, any progress?

**Comment by adelin-b** [comment] 2020-10-13 04:56
Indeed the problem is not that the pattern isnt respected its that there is a bug that dont register changes when clicking `Apply` button, you have to close the window instead and it will work

**Comment by purnimagupta** [comment] 2021-01-10 12:39
Closing the window without clicking on OK works for me!

**Comment by piyushraja** [comment] 2021-09-06 16:18
> Closing the window without clicking on OK works for me!

This worked for me too! Thanks!

**Comment by adelin-b** [comment] 2021-09-06 17:24
I think that a ui bug like an apply button that don't works shouldn't stay 2 years open, it probably went under mainteneur radar

**Comment by teejee2008** [comment] 2021-09-25 05:34
Why two entries for the same path? Keep any one entry. The UI will remove duplicates like this one.

`node_modules` will exclude the folder
`node_modules/**` will keep the folder and exclude the contents

**Closed by teejee2008** 2021-09-25 05:34 UTC
