### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by WineBottles** [teejee2008/timeshift#823] opened 2021-11-02 12:21 UTC
Current version: 21.09.1

When using Timeshift on a computer that is using dark mode it is blinding upon launching Timeshift.

Please add a dark mode option.

Alternative solution: please add a dark grey mode.

**Comment by Githob2021** [comment] 2021-11-02 16:57
Here is an example of the color clash it crashes.
![355768C6-3106-4516-888D-EC8114C5B8EC](https://user-images.githubusercontent.com/93590337/139910743-4f5c5c9d-d357-4d0a-bffa-74e8924092ee.png)

**Comment by maklamj** [comment] 2021-11-02 18:19
Use a dark mode GTK theme then it'll be dark..
On KDE: https://userbase.kde.org/System_Settings/GNOME_Application_Style_(GTK)

**Comment by OwenAR** [comment] 2021-11-08 02:32
Hi! I've got the same problem, but I think this is actually a bug with the kde/plasma DE (desktop environment).

That is, if you go into your system settings (`systemsettings5` I mean)
then under "Application Style"
you'll find "Configure GNOME/GTK Application Style..."
(or something like that -- exactly what they call it seems to depend on the exact kde/plasma version)

Myself, I'm on Kubuntu 20.04.3
which has "KDE 5.68.0 / Plasma 5.18.5"
and I'm using the Breeze-Dark theme,
and I set GTK to use that too
(in both GTK 2 and 3 -- they've listed separately in this version of kde/plasma)

But for some reason,
that always stops working after I reboot
|
like, it still *says* the GTK2/3 themes are set to use Breeze-Dark
but it never actually has an *effect* until after I select them and click apply *again*
(and sometimes I have to do it twice).

---
I've found references to other people having the same (or a similar?) problem
eg
https://forum.kde.org/viewtopic.php?f=309&t=170722&p=444411&hilit=gtk+theme+restart&sid=0e4b6a9d323ac1701bbeac2d307c0ac5#p444411

and while experimenting with newer versions of kde/plasma on other distros,
I've seen an even *worse* problem where I couldn't get the GTK theme settings to have any effect *at all*...

Trying to ask about it has been sitting on my todo-list for ages
(like, *obvious* thing to do would be to make a kde forum account and ask *that* person if they ever found a solution)
but I just haven't been able to work up the mental/emotional energy yet...

---
...
EDIT:
Okay yeah, it turns out this *is* related to another bug I posted report about just before this
#829 
(which renders the GUI unusable)
cuz I just used kde system settings to set the gtk theme,
and I end up with *this*:
![2021-11-07-182805_1366x768_scrot](https://user-images.githubusercontent.com/3036957/140675134-d2e5a797-b733-4d30-837f-fa40a4ae557f.png)

(Although in that case, it happened even though I  *hadn't* touched the GTK theme settings...)

**Comment by teejee2008** [comment] 2022-05-28 08:00
Unable to reproduce. Closing this one.

**Closed by teejee2008** 2022-05-28 08:00 UTC
