### ISSUE TITLE
Lost snaptshots

### ISSUE THREAD

**Issue by JosuGZ** [teejee2008/timeshift#272] opened 2018-08-06 11:54 UTC
I have the tool configured to keep 5 daily snapshots, and 5 monthly snapshots. It only keeps one of each, so I don't have snapshots older than today.

**Comment by teejee2008** [comment] 2018-09-01 09:49
Is there sufficient free space on the drive? Check the logs in /var/log/timeshift

**Comment by cmulk** [comment] 2018-11-14 22:42
I'm seeing what might be related behavior. I have the daily snapshots set to 5, with 5 current snapshots. A new daily snapshot runs and I expect it to remove the oldest and still end up with 5 total snapshots. Instead it has deleted the 3 oldest snapshots, leaving a total of 3 remaining. 

This is on a btrfs setup. Log attached
[timeshift_log.txt](https://github.com/teejee2008/timeshift/files/2582934/timeshift_log.txt)

**Comment by cmulk** [comment] 2018-11-15 03:53
After some additional testing I realized this behavior is caused by cases where daily snapshots are missed for a period of time. Timeshift is removing snapshots older than 5 days rather than keeping 5 snapshots. To me this seems inconsistent with how it is described in the GUI settings and can easily lead to snapshots getting removed when the user isn't planning on it. 

See attached log of my test
[timeshift_test.txt](https://github.com/teejee2008/timeshift/files/2583593/timeshift_test.txt)

**Comment by Maaartinus** [comment] 2018-12-31 14:11
This is even worse. Today, I started the computer after not having used it for one week. There should be 5 snapshots kept, but timeshift created a new one and deleted all old ones. So the only snapshot I have is the current state, there's actually no backup at all.

**Comment by teejee2008** [comment] 2019-01-02 03:12
Fixed. Duplicate of #362.

**Closed by teejee2008** 2019-01-02 03:12 UTC
