### ISSUE TITLE
Timeshift RSYNC backups are not including any hidden files

### ISSUE THREAD

**Issue by jacobcantele** [teejee2008/timeshift#15] opened 2017-09-03 20:13 UTC
When I'm running Timeshift backups, none of the hidden files in my Home folder or root are being included in the system backup. I'm using the RSYNC method of backup.

**Comment by teejee2008** [comment] 2017-09-10 16:56
Please post the contents of file "exclude.list" in the snapshot folder

**Comment by jacobcantele** [comment] 2017-09-14 03:27
Wow, there is a ton in there and I'm not sure why? I definitely didn't exclude anything intentionally. Here is what is appearing:

/dev/*
/proc/*
/sys/*
/media/*
/mnt/*
/tmp/*
/run/*
/var/run/*
/var/lock/*
/var/spool/*
/var/lib/docker/*
/lost+found
/timeshift/*
/timeshift-btrfs/*
/data/*
/cdrom/*
/etc/timeshift.json
/var/log/timeshift/*
/var/log/timeshift-btrfs/*
/root/.thumbnails
/root/.cache
/root/.dbus
/root/.gvfs
/root/.local/share/[Tt]rash
/home/*/.thumbnails
/home/*/.cache
/home/*/.dbus
/home/*/.gvfs
/home/*/.local/share/[Tt]rash
/root/.mozilla/firefox/*.default/Cache
/root/.mozilla/firefox/*.default/OfflineCache
/root/.opera/cache
/root/.kde/share/apps/kio_http/cache
/root/.kde/share/cache/http
/home/*/.mozilla/firefox/*.default/Cache
/home/*/.mozilla/firefox/*.default/OfflineCache
/home/*/.opera/cache
/home/*/.kde/share/apps/kio_http/cache
/home/*/.kde/share/cache/http
/home/galago/Downloads/backup/***
+ /root/***
+ /home/galago/***
+ /root/.**
/root/**
+ /home/*/.**
/home/*/**

**Comment by teejee2008** [comment] 2017-09-18 17:39
These are locations which are excluded by default. The contents of these directories are not useful and including them will cause problems while restoring your system. 

Anything starting with a + will be included instead of being excluded.

Could you post a screenshot of the Exclude list in Settings window? I can see some extra entries at the end which are not part of the default exclude list.

**Comment by jacobcantele** [comment] 2017-09-18 18:10
Sure thing:

![screenshot from 2017-09-18 13-09-11](https://user-images.githubusercontent.com/10467486/30557059-ac3eab58-9c72-11e7-9f7b-34093c050b68.png)

**Comment by jacobcantele** [comment] 2017-09-23 17:55
Any thoughts here?

**Comment by teejee2008** [comment] 2017-10-01 04:51
Your setup looks fine. Not sure what the issue is. Try v17.10 and let me know if it works for you.

In v17.10, remove everything from the Filters list. Then go to the **Users** tab in Settings and select the "Include hidden files" option for the user.

**Comment by teejee2008** [comment] 2018-02-05 05:44
Please update to v18.2 and re-open if issue persists

**Closed by teejee2008** 2018-02-05 05:44 UTC
