### ISSUE TITLE
Timeshift doesn't work on Fedora 31 either 32

### ISSUE THREAD

**Issue by cann357** [teejee2008/timeshift#623] opened 2020-06-17 03:11 UTC
Hello the issue is basically that Timeshift isn't working as well on my Fedora system either 31 wich i had and wich i actually have that is 32 the bug is this prompt (on spanish):
  La particion tiene una estructura de subvolumen no compatible.
  Actualmente solo son compatibles las estructuras tipo Ubuntu con subvolumenes @ y @home
Basically it says, that it is not compatible, my subvolumes cause they are not a @ and @home
and that is very annoying cause that appeared before when i tried to create the 1st retore point in btfrs mode and my main partition is btfrs kind of and just didnt work so then i tried to do it on rsync mode and it works but now im trying to restore to a previous state of my system and i just realize i cant cause that prompt appears again and dont let me restore anything so i dont know if it is a fedora issue or timeshift or both when i try to use it as well, to reproduce the bug just install timeshit on fedora and try to use it that system, i'm on:
Linux 5.6.18-300.fc32.x86_64 
Fedora 32 (KDE Plasma)
The app version is the latest (i'm not pretty sure about the exact version but i'm allways try to have my system up to date at all)

So i really need to know if you can help me with this issue i hope so, and thanks beforehand. Have a nice day.
![cap](https://user-images.githubusercontent.com/61927371/84850803-9ef00f80-b026-11ea-824b-6638c3df1802.png)

**Comment by JHrenyk** [comment] 2020-08-09 18:58
Fedora installs use the sub volumes root and home instead of the normal @ for root and @home for home. I'd really like to move to Fedora but I really don't want to give up timeshift and Fedora really doesnt want me to rename my sub volumes on install

**Comment by ShrirajHegde** [comment] 2021-02-13 12:20
> Fedora installs use the sub volumes root and home instead of the normal @ for root and @home for home. I'd really like to move to Fedora but I really don't want to give up timeshift and Fedora really doesnt want me to rename my sub volumes on install

can't just timeshift support a different subvolume name?

**Comment by wmutschl** [comment] 2021-02-13 12:30
You can use my fork of timeshift for this: https://github.com/wmutschl/timeshift
I am still working on implementing a GUI option to change the names, but in my fork you can already change the name in the config file of timeshift.

**Comment by wmutschl** [comment] 2021-02-13 12:31
Alternatively, you can rename the subvolumes after installation. I have written down the steps [here](https://mutschler.eu/linux/install-guides/fedora-btrfs/)

**Comment by ShrirajHegde** [comment] 2021-02-13 17:01
> Alternatively, you can rename the subvolumes after installation. I have written down the steps [here](https://mutschler.eu/linux/install-guides/fedora-btrfs/)

I already installed it with @root subvolume, but still, BTRFS won't work

I have a separate /boot partition with ext4

![image](https://user-images.githubusercontent.com/66936172/107855839-d5e32300-6e4a-11eb-85b3-aa9ee066191b.png)

![image](https://user-images.githubusercontent.com/66936172/107855888-2c506180-6e4b-11eb-9875-89bbb829fb63.png)

Anyway to fix this??

Home is in separate partition inside subvolume @home too.

**Comment by wmutschl** [comment] 2021-02-13 18:42
it should be called just @ and not @root

**Comment by ShrirajHegde** [comment] 2021-02-13 19:26
> it should be called just @ and not @root

can I just rename it in nautilus??

**Comment by wmutschl** [comment] 2021-02-13 19:34
it can be done (with root privileges) but it is best done from a live usb stick! you also have to adapt your /etc/fstab file. BUT if you dont know what you are doing here, please stop as this will very likely make your computer not boot anymore. again take my guide above as resource if you do wanna try.

**Comment by ShrirajHegde** [comment] 2021-02-13 19:40
No, I have experience with BTRFS (got Timeshift working on Arch), I am doing the changes from Ubuntu and I have made the adaptions in fstab necessary.

what is `x-systemd.device-timeout=0 ` in mount options?

**Comment by ShrirajHegde** [comment] 2021-02-13 20:33
> Alternatively, you can rename the subvolumes after installation. I have written down the steps [here](https://mutschler.eu/linux/install-guides/fedora-btrfs/)

Everything else is clear, how to update grub config from live environment??

**Comment by wmutschl** [comment] 2021-02-15 20:01
chroot into your system and run `grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`, again it is outlined in the link given above. I think you can close this issue. If you have other questions, feel free to write me an email.

**Comment by ShrirajHegde** [comment] 2021-02-16 05:18
> chroot into your system and run `grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`, again it is outlined in the link given above. I think you can close this issue. If you have other questions, feel free to write me an email.

Not my issue, chroot didn't work so I reversed the rename and did it in the system, everything works and I even had to restore once. Thanks

**Comment by jwatt** [comment] 2021-06-19 22:07
Hopefully the patches for issue #423 will fix the GRUB issue.

**Comment by teejee2008** [comment] 2021-09-25 05:07
Duplicate of #764

**Closed by teejee2008** 2021-09-25 05:07 UTC
