### ISSUE TITLE
hdd become readonly

### ISSUE THREAD

**Issue by MedShake** [teejee2008/timeshift#263] opened 2018-07-24 16:29 UTC
Hi

I use timeshift with linux mint 19. 
After the boot timeshift make the job but after the first snapshot of the day, the hard drive turn to read only mode. 
I searched the web but I can't find any other case. 
Thanks for your help !

**Comment by ehtron** [comment] 2018-07-25 12:58
Hi :)
is the same problem like my issue
ts dont umount the mounted partition... and the partition owned rood after backup.

https://github.com/teejee2008/timeshift/issues/248

**Comment by MedShake** [comment] 2018-07-25 14:29
Thanks for your answer !
I'm not sure to understand well. 
Can we do something or it's just a bug in the software and we need to wait for correction ?

B.

**Comment by ehtron** [comment] 2018-07-25 14:36
Hi :)
we must wait for correct the bug. 
or write a own backup weekly batch..  i have do that, but all my descriptions are german... 
we should wait for bugfix
regards ehtron

**Comment by teejee2008** [comment] 2018-09-01 09:31
closing duplicate of #248

**Closed by teejee2008** 2018-09-01 09:31 UTC
