### ISSUE TITLE
[Feature request] Support for other btrfs subvolume layouts

### ISSUE THREAD

**Issue by Chrysostomus** [teejee2008/timeshift#9] opened 2017-05-27 15:43 UTC
Would this be feasible to add? It seems that just having @ and @home is not enough, but there must also  be no other subvolumes. This limits the usability severely. Which is a shame, because this is one the nicest guis to manage btrfs snapshots.

**Comment by teejee2008** [comment] 2017-05-27 16:33
What other subvolumes do you have on your system other than @ and @home ?

**Comment by Chrysostomus** [comment] 2017-05-27 16:50
@snapshots (/.snapshots) to store snapper snapshots outside root volume, @cache (/var/cache/pacman/pkg) to exclude package manager cache from snapshots, @log (/var/log) to avoid losing log files when restoring a snapshot.

**Comment by Chrysostomus** [comment] 2017-05-27 19:01
Requirement of having @ and @home is acceptable and nonproblematic, but requirement of not having other subvolumes is too limiting. I would package and include timeshift in manjaro repos, but this is one of the two issues making me hesitate (the other being the fact that it does not build with up to date vala version). 

Anyway, thank you for creating this excellent application!

**Comment by Chrysostomus** [comment] 2017-05-29 09:45
Aah, it seems that it might be bug here actually. I made a new installation with just @ and @home subvolumes. I still got the same error message (Not supported - The system partition has an unsupported subvolume layout...).

**Comment by teejee2008** [comment] 2017-09-10 17:07
There's no requirement of not having other subvolumes. It should work as long as @ and @home are available. I'm not sure why you are getting that error.

I'll be adding an option to specify the subvolumes to backup and restore. But it will take time to implement.

**Comment by Chrysostomus** [comment] 2017-09-10 17:26
Thank you. Maybe the issue is with the package (manjaro, built from AUR) and not the code. I'll do some further experiments. It seems that the btrfs side was just simply broken on my end.

**Comment by aneesh-neelam** [comment] 2017-11-28 19:40
I believe the subvolumes used by Anaconda (Fedora's installer) by default are named slightly different. Timeshift can't recognize this as a BTRFS volume with the necessary subvolumes. 

```
[aneeshneelam@Titan mapper]$ sudo btrfs subvolume list /
ID 257 gen 12099 top level 5 path home
ID 258 gen 12099 top level 5 path root
ID 264 gen 12009 top level 258 path var/lib/machines
```

Hope this helps.

**Comment by Chrysostomus** [comment] 2018-02-11 17:13
@teejee2008 Related to this issue, could you help me satisfy the demands of timeshift btrfs mode? I develop manjaro-architect, the cli-installer of Manjaro linux. I have had reports that Manjaro installed by Calamares works with timeshift, while system installed with manjaro-architect does not. Since there are talks of including timeshift with Manjaro by default, I would like to make sure it works with the defaults. (https://github.com/manjaro/release-plan/issues/170)

Here is an example fstab generated by manjaro-architect:
```

# /dev/sda4 UUID=b6db6b9b-e2a1-4e97-9165-bdd444552544
PARTUUID=9f736e9d-551b-4eb5-8588-b04d136dddda /           btrfs       rw,noatime,compress=lzo,ssd,space_cache,commit=120,subvol=@ 0 0

# /dev/sda4 UUID=b6db6b9b-e2a1-4e97-9165-bdd444552544
PARTUUID=9f736e9d-551b-4eb5-8588-b04d136dddda /home       btrfs       rw,noatime,compress=lzo,ssd,space_cache,commit=120,subvol=@home 0 0

# /dev/sda4 UUID=b6db6b9b-e2a1-4e97-9165-bdd444552544
PARTUUID=9f736e9d-551b-4eb5-8588-b04d136dddda /var/cache  btrfs       rw,noatime,compress=lzo,ssd,space_cache,commit=120,subvol=@cache  0 0

# /dev/sda1 UUID=3B0B-4438
PARTUUID=6336dbd3-1759-450c-933e-4fb329659c67 /boot/efi   vfat        rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0

```

And here is an example fstab generated by Calamares:
```

# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>             <mount point>  <type>  <options>  <dump>  <pass>
UUID=5e96c4a7-f6f5-4b46-b959-38cc834ce911 swap           swap    defaults,noatime 0 2
UUID=E903-AF8F                            /boot/efi      vfat    defaults,noatime 0 2
UUID=65fc5e68-b757-440e-ae4d-fe35e8033181 /              btrfs   subvol=@,defaults,noatime,space_cache,autodefrag,discard,compress=lzo 0 1
UUID=65fc5e68-b757-440e-ae4d-fe35e8033181 /home          btrfs   subvol=@home,defaults,noatime,space_cache,autodefrag,discard,compress=lzo 0 2
tmpfs                                     /tmp           tmpfs   defaults,noatime,mode=1777 0 0
```

What does timeshift use to determine if "The system partition has an unsupported subvolume layout"? 

For further data, subvolume layout generated by manjaro-architect:

```
btrfs subvolume list /
ID 257 gen 33 top level 5 path @
ID 258 gen 33 top level 5 path @home
ID 259 gen 29 top level 5 path @cache
ID 260 gen 11 top level 5 path @snapshots
ID 263 gen 16 top level 257 path var/lib/machines

```

Does the order of the mount options in fstab perhaps matter?

**Comment by teejee2008** [comment] 2018-02-12 17:04
As mentioned in previous comments, Timeshift only checks if @ and @home subvolumes are present. I'm not sure what the issue is.
I'm using a Manjaro system installed with Calamares and Timeshift works fine with it. I'll try with Manjaro architect and let you know.

**Comment by Chrysostomus** [comment] 2018-02-12 21:00
Thanks! I'll make a calamares install too for comparison.

**Comment by teejee2008** [comment] 2018-02-13 11:32
I found the issue. The @cache mount was causing a problem. It will be fixed in next release.

BTW, Manjaro architect appends "subvol" parameter twice to the fstab line.
```
# /dev/sdc1
UUID=e00a72be-53dc-41ce-b1c6-e2d649b9d87e	/         	btrfs     	rw,noatime,compress=zlib,nossd,space_cache,autodefrag,subvolid=257,subvol=/@,subvol=@	0 0

# /dev/sdc1
UUID=e00a72be-53dc-41ce-b1c6-e2d649b9d87e	/home     	btrfs     	rw,noatime,compress=zlib,nossd,space_cache,autodefrag,subvolid=258,subvol=/@home,subvol=@home	0 0

# /dev/sdc1
UUID=e00a72be-53dc-41ce-b1c6-e2d649b9d87e	/var/cache	btrfs     	rw,noatime,compress=zlib,nossd,space_cache,autodefrag,subvolid=259,subvol=/@cache,subvol=@cache	0 0
```

**Comment by Chrysostomus** [comment] 2018-02-14 04:45
Double subvol entry is fixed in git already.

Thanks, it will be nice to have this issue resolved!

**Comment by teejee2008** [comment] 2018-04-01 15:27
Fixed in v18.4

**Closed by teejee2008** 2018-04-01 15:27 UTC
Labels: bug, enhancement

**Comment by Chrysostomus** [comment] 2018-04-01 15:44
Thanks!

**Comment by kaefert** [comment] 2019-04-14 09:34
I have two Manjaro KDE Laptops, the one I setup first did work but the second one gives me the `unsupported subvolume layout` error when trying to create a snapshot.

I think the layout looks just as it should:

> $ sudo btrfs sub li /
ID 257 gen 11330 top level 5 path @
ID 258 gen 23 top level 5 path @home
ID 266 gen 81 top level 257 path var/lib/portables
ID 267 gen 81 top level 257 path var/lib/machines

See also https://forum.manjaro.org/t/timeshift-stopped-working/83022
