### ISSUE TITLE
invalid mouse cursor in kde

### ISSUE THREAD

**Issue by milad0123** [teejee2008/timeshift#8] opened 2017-05-25 10:17 UTC
hi.
 kde neon with kde  5.8.7 lts.
![ffthh](https://cloud.githubusercontent.com/assets/19423078/26446367/f87df020-4158-11e7-850b-ba5f5b52d928.jpeg)

**Comment by Chrysostomus** [comment] 2017-05-27 15:41
The issue is not kde specific, but happens across environments.

**Comment by NikoKrause** [comment] 2017-09-09 11:48
Which Icon Theme do you use? I saw this once in a [different place in Cinnamon](https://github.com/linuxmint/Cinnamon/issues/3728) with the Capitaine Cursors.
The Capitaine Cursor have been fixed: https://github.com/keeferrourke/capitaine-cursors/issues/10

Maybe it's the same issue? If you're using the Capitaine Cursors, can you try to update them?

**Comment by teejee2008** [comment] 2017-10-01 04:46
Fixed in v17.10

**Closed by teejee2008** 2017-10-01 04:46 UTC
Labels: bug
