### ISSUE TITLE
Bad file explorer in Kubuntu 18.04

### ISSUE THREAD

**Issue by ghost** [teejee2008/timeshift#219] opened 2018-06-19 07:38 UTC
After selecting a specific backup and after clicking the browse button, the default file browser Dolphin will not open, but open the Gwenview image viewer.

Steps needed to repeat the error:
- install Kubuntu
- install Timeshift
- create backup
- open backup

I also checked the manjaro and there is the same problem, also the problem concerns more the environment, not the system.

**Comment by teejee2008** [comment] 2018-06-23 13:37
You need to fix the associations for the inode/directory mime type on your system (check on Google).

Timeshift executes **xdg-open** to open snapshot folder in file manager. xdg-open uses the default file/folder associations on your system. Your system seems to be configured to open with Gwenview. You need to change that to Dolphin.

**Comment by emanuc** [comment] 2018-07-08 18:18
I have a problem, here are some logs, I hope it is useful:
Kubuntu 18.04
Timeshift 18.6.1

> emanu@emanuc:~$ timeshift-launcher
Configurazione caricata: /etc/timeshift.json
/dev/sda1 is mounted at: /mnt/timeshift/backup, options: rw,relatime,compress=lzo,ssd,space_cache,autodefrag,subvolid=5,subvol=/
Executing Dolphin as root is not possible.
Executing Dolphin as root is not possible.
Warning: program returned non-zero exit code #1
WARNING: You don't seem to have any mimeinfo.cache files.
Try running the update-desktop-database command. If you
don't have this command you should install the
desktop-file-utils package. This package is available from
http://freedesktop.org/wiki/Software/desktop-file-utils/
Can't call method "get_value" on an undefined value at /usr/bin/mimeopen line 159.
[19190:19190:0708/201321.389564:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: firefox: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium-browser: not found
[19216:19216:0708/201321.442664:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening '/mnt/timeshift/backup/timeshift-btrfs/snapshots'
Configurazione salvata: /etc/timeshift.json

**Comment by teejee2008** [comment] 2018-07-09 02:33
According to the error message, your system does not support running file manager (Dolphin) as root. You won't be able to browse the snapshots.

**Comment by willem179** [comment] 2018-07-09 15:15
I had the same problem on Lubuntu: Pressing the browse button opens Audacious.
The reason is that xdg-open is not really meant be used by the root account. Root is no
desktop user.

Timeshift runs under the root account and xdg-open finds no .desktop file for mime type
inode/directory, because the root account has no .desktop files at all.
xdg-open then defaults to /usr/share/applications/defaults.list which
happens to be the unmodified "gnome" list in Lubuntu, containing the following line:
`inode/directory=nautilus-folder-handler.desktop`

But on Lubuntu the nautilus-folder-handler.desktop item does not exist.
Lubuntu does not use nautilus.
Apparently the system then takes the first application that has inode/directory in
its accepted mime types, in my case Audacious.

The problem could be solved for Lubuntu by changing the offending line in
/usr/share/applications/defaults.list to:
`inode/directory=pcmanfm.desktop`
but I am not sure if that survives possible updates of the system.

A better solution is to add a new defaults.list file to the root account:
`/root/.local/share/appplications/defaults.list`
containing only these two lines:

```
inode/directory=pcmanfm.desktop
x-directory/normal=pcmanfm.desktop
```

**Comment by Djaler** [comment] 2019-02-04 16:58
@teejee2008 can you check this please?

**Comment by teejee2008** [comment] 2019-02-07 16:12
Files in the snapshot directory are owned by root. Opening it in a file manager running as a normal user is not useful.

I'll change this so that the file manager is opened directly instead of using xdg-open.

**Comment by gcjuan** [comment] 2019-02-22 12:20
For now, just before it is fixed on v19.06 as @teejee2008 said above (June 30, 2019 is the latest [planned day for release](https://github.com/teejee2008/timeshift/milestone/7)), you can do the [workaround](https://github.com/teejee2008/timeshift/issues/219#issuecomment-403514624) commented by @willem179.

I share with you a little video of my issue on KDE neon 5.15 (it opened VScode instead of the file explorer) and the corresponding steps I made to fix it:

https://streamable.com/wzpa8

**Comment by JackDinn** [comment] 2019-06-20 11:18
is this still due to be fixed for KDE in a few days ? I have not been able to use timeshift for a long time and am looking forward to using it again. 
I have tried the workarounds but Manjaro KDE does not allow dolphin to run as root so none of them worked.
Thx.

**Comment by teejee2008** [comment] 2021-09-25 05:25
This is fixed. Duplicate of #186

**Closed by teejee2008** 2021-09-25 05:25 UTC
Labels: question
