### ISSUE TITLE
Timeshift ppa is purged, but it still creates a massive /timeshift folder 

### ISSUE THREAD

**Issue by ostrol** [teejee2008/timeshift#406] opened 2019-03-23 16:21 UTC
As timeshift started creating unmanageable massive sized /timeshift folder, I purged the ppa, deleted the /timeshift folder manually. But, it still creates a /timeshift folder of a massive size. I checked the filesystem, and the /timeshift was not there, then when I try to boot back, it had created a massive sized folder, taking all fee space left. I have to delete that folder from another Linux to get the free space back. **What is creating this /timeshift folder?** It looks more like a virus now!

This is happening every few days.

When I put the laptop off, there was no /timeshift folder in the root filesystem, but when I started the laptop now, the /timeshift folder is there and it is more than 10GB. Again, I deleted it manually. Now, again theer is nothing called timeshift anywhere in the system (except few icons), so the whole thing looks more like a virus, rather than a helpful app. Can you tell me how to get rid of this problem? This is serious!

**Comment by teejee2008** [comment] 2019-03-24 12:05
Have you uninstalled it properly? Type `timeshift` in a command window and it should say "command not found".

Remove Timeshift completely using `sudo apt purge timeshift`. After this snapshots will not get created in /timeshift folder. Delete existing snapshots using `sudo rm -rf /timeshift`

**Comment by ostrol** [comment] 2019-03-25 07:57
Timeshift was purged properly and the existing snapshots. Nothing in the system other than few icons named timeshift. The folder/timeshift didn't appear today morning, but would in a day or two.

**Comment by ostrol** [comment] 2019-03-26 08:23
And, it is back again! 
And, has 8.2GB.
This app, or some part of it must be hidden somewhere, maybe in the kernel, I have no idea. Now, it is acting as **a virus**. It is just creating the/timeshift folder and adding stuff to it. 

I'll be deleting it again, manually. Could you find a way to get rid of this problem?

**Comment by teejee2008** [comment] 2019-03-26 16:31
Based on your description it seems that it is still installed.

Answer the following:
1) How are you un-installing Timeshift? (provide the exact commands that you used). Simply purging the PPA is not enough as the "ppa-purge" command will install it from the official repository (if you are using Linux Mint)
2) After un-installing, type 'timeshift' in a terminal and let me know the message you get. (It should say "command not found" - **please confirm this** - if the command doesn't exist there's no way that the snapshots will get created again).
3) "Nothing in the system other than few icons named timeshift." - what do you mean by this? After uninstalling, it should not appear in application menu or anywhere else.

**Comment by ostrol** [comment] 2019-03-27 07:53
1) I had tried timeshift on Ubuntu. Ppa purge uninstalled everything. Before doing the ppa purge, I deleted the /timeshift folder manually, by opening the file manager as root and deleting that folder. Deleting, not moving to trash.
2) I confirm the "command not found" in the terminal.

> $ timeshift
> Command 'timeshift' not found, but can be installed with:
> sudo apt install timeshift

3) Ah, those icons. They are in some icons folder in /usr/share/icons, has nothing to do with timeshift. Some icons developers have this type of icons. They are not anywhere in application menu, only in their own icon folders. 

the /timeshift folder was there today and was 7.8GB. I just deleted that.

**Comment by ostrol** [comment] 2019-04-09 06:02
Have you found a way out from this problem, @teejee2008?
Has your app got inside the kernel? What makes the /timeshift get created, when the timeshift package is not in the system? This is the first time, I had this kind of thing happening in Linux!

**Comment by teejee2008** [comment] 2019-04-10 15:48
You need to investigate what is going on in your system.

Are there other people using your computer? Are you dual-booting another Linux system that has Timeshift installed? Is the drive shared over LAN?

**Comment by ostrol** [comment] 2019-04-10 20:21
No other people uses this computer.
I am dual booting with Linux Mint, which has Timeshift installed by default. After your last reply checked that install and the timeshift settings. This is the 1st time, I looked in that settings in Linux Mint. It had the location to the nearest partition by number, and was creating snapshots daily. I moved that location manually to a free data partition, but it is a **bug.** It maybe a bug with Linux Mint, not checking up the Timeshift settings, or it is a bug with Timeshift itself, by automatically saving to the nearest by number Linux partition. 

**Solution:** when anyone installs Timeshift none of the partitions should be marked at all. It should be left to the user to mark a partition. I just checked installing Timeshift in another distro dual booted in the same laptop. That too had by default the same (nearest by number) Linux partition marked as the location to save the snapshots. This happens without telling the user. So, none should be marked by default. 

I found the problem, by asking you, and being somewhat troublesome to you, but most of the users even don't know what happens with their partitions losing space and sometimes never booting, for lack of space. This should be corrected.

**Comment by teejee2008** [comment] 2019-04-11 16:44
When you run Timeshift for the first time it displays a Setup Wizard. It will ask you where to save the snapshots. You can either select a location, or continue with the default option. The default option is to save snapshots to system partition. If you don't want it to be saved there, you need to change it when the option is presented to you.

Providing a default option is not a bug. The problem here is that you didn't pay attention when you set up the application. You seem to be using this app without any understanding of what it does and which location is selected for saving snapshots. And your response is to call it a bug and ask for removing the default selections?

You are facing this issue for more than 2 weeks and yet you didn't remember that you are dual-booting another Linux system which has Timeshift installed and running?

As for taking up disk space... yes, that's what this application does... it creates snapshots... which take up disk space. You need to be aware of where you are saving snapshots and whether you have enough free space.

I'm closing this one.

**Closed** 2019-04-11 16:45 UTC
